### ISSUE TITLE
Get some stats into a database for testing

### ISSUE THREAD

**Issue by ThePianoDentist** [charlesastaylor/openPUBG#2]
Either clone this https://github.com/Hormold/pubg
or implement ourselves

**Comment by charlesastaylor** [comment]
We are so collaborating rn. I'll try and connect a database later but was just reading through the github and some reddit posts about it. Says something about having to update the token used to access the web server every few hours. Does that mean pubg.me is somehow constanlty running a copy of the game somewhere to keep updating its access token or am I getting it all wrong?

**Comment by ThePianoDentist** [comment]
yeah possibly. 

I think theyre going to have an out-of-game  stats later on. so we can just hook into that. but for now yeah might need game running

**Comment by ThePianoDentist** [comment]
Got some fake stats script.

Not sure its worth using https://github.com/Hormold/pubg. when we can just work on other stuff until base-site ready to be released/used
